apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
        - name: worker
          image: asia-south1-docker.pkg.dev/microservices-786/doc-registry/worker-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  type: LoadBalancer
  selector:
    app: worker-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
