name: Deploy Cloud Doc Pipeline

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-south1
  ZONE: asia-south1-a
  CLUSTER_NAME: document-cluster
  GAR_URL: asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/doc-registry
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials document-cluster \
            --zone asia-south1-a \
            --project ${{ secrets.GCP_PROJECT_ID }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

#      - name: Terraform Init & Apply (infra/)
#        working-directory: ./infra
#        run: |
#          terraform init
#          terraform apply -auto-approve -var="gcp_credentials=$GOOGLE_CREDENTIALS" -var="project_id=$PROJECT_ID"

#      - name: Build & Push Upload API Image
#        run: |
#          docker build -t $GAR_URL/document-service ./document-service
#          docker push $GAR_URL/document-service
#
#      - name: Build & Push Worker API Image
#        run: |
#          docker build -t $GAR_URL/worker-service ./worker-service
#          docker push $GAR_URL/worker-service

      - name: Configure kubectl to GKE
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --zone $ZONE --project $PROJECT_ID

      - name: Deploy to GKE
        run: kubectl apply -f ./k8s
