name: Deploy Cloud Doc Pipeline

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-south1
  ZONE: asia-south1-a
  CLUSTER_NAME: document-cluster
  GAR_URL: asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/doc-registry

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Terraform Init & Apply (infra/)
        working-directory: ./infra
        run: |
          terraform init
          terraform apply -auto-approve -var="project_id=$PROJECT_ID"

      - name: Build & Push Upload API Image
        run: |
          docker build -t $GAR_URL/upload-service ./upload-service
          docker push $GAR_URL/upload-service

      - name: Build & Push Worker API Image
        run: |
          docker build -t $GAR_URL/worker-service ./worker-service
          docker push $GAR_URL/worker-service

      - name: Configure kubectl to GKE
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --zone $ZONE --project $PROJECT_ID

      - name: Deploy to GKE
        run: kubectl apply -f ./k8s
